name: Run SalesToBigQuery Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Write Google Application Credentials to file
      run: |
        echo "Writing Google Application Credentials to $HOME/credentials.json"
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/credentials.json
        echo "Credentials file created at $HOME/credentials.json"
        echo "Directory contents of $HOME:"
        ls -l $HOME
        echo "Printing directory of credentials file:"
        dirname $HOME/credentials.json
        echo "Contents of the credentials file (first 1000 lines):"
        head -n 1000 $HOME/credentials.json
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/credentials.json

    - name: Run SalesToBigQuery script
      run: python SalesToBigQuery.py
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/credentials.json
