name: Run Bookings Script

on:
  schedule:
    - cron: '*/15 9-15 * * 4-6'
    - cron: '*/15 9-15 * * 1'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gspread oauth2client pandas

      - name: Verify Environment Variables and Set Credentials
        run: |
          echo "Checking if environment variables are loaded..."
          if [ -z "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
            echo "Google Application Credentials JSON is missing or not set correctly."
            exit 1
          else
            echo "Google Application Credentials JSON is loaded successfully."
            echo "$GOOGLE_APPLICATION_CREDENTIALS" > credentials.json
            echo "Credentials saved to credentials.json"
            echo "Credentials length: ${#GOOGLE_APPLICATION_CREDENTIALS}"
            echo "Credentials (partial): ${GOOGLE_APPLICATION_CREDENTIALS:0:100}"
          fi
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Run the script
        run: |
          if [ -f "Bookings.py" ]; then
            echo "File Bookings.py found. Running script."
            export GOOGLE_APPLICATION_CREDENTIALS=credentials.json
            python Bookings.py
          else
            echo "Error: Bookings.py not found."
            exit 1
          fi
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Print Directory Structure After Script Execution
        run: |
          echo "Current working directory after script execution:"
          pwd
          echo "Directory contents after script execution:"
          ls -la
          if [ -d "data" ]; then
            echo "Contents of 'data' directory after script execution:"
            ls -la data
          else
            echo "'data' directory does not exist."
          fi
          echo "Checking if CSV file exists at full path:"
          if ls data/Bookings_*.csv 1> /dev/null 2>&1; then
            echo "CSV file(s) found:"
            ls data/Bookings_*.csv
          else
            echo "CSV file not found."
          fi
        continue-on-error: true

      - name: Upload CSV file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: csv-file
          path: data/Bookings_*.csv
