name: Run SumUp Data Script

on:
  schedule:
    # Runs every hour between 12 PM and 5 PM, from Thursday to Monday
    - cron: '0 12-17 * * 4-7'  # Thursday (4) to Monday (7), every hour from 12 PM to 5 PM

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Replace with your required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run the script
        env:
          SUMUP_API_KEY: ${{ secrets.SUMUP_API_KEY }}  # Pass the secret as an environment variable
        run: |
          python TotalSales.py  # Replace with your script filename
