name: Run SumUp Data Script

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Print Directory Structure Before Script Execution
        run: |
          echo "Current working directory before script execution:"
          pwd
          echo "Directory contents before script execution:"
          ls -la

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          set -x
          python -m pip install --upgrade pip
          pip install -r requirements.txt || { echo 'Dependency installation failed'; exit 1; }
          pip install google-cloud-bigquery google-auth google-auth-oauthlib google-auth-httplib2 || { echo 'Google Cloud dependencies installation failed'; exit 1; }
        env:
          SUMUP_API_KEY: ${{ secrets.SUMUP_API_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Verify Environment Variables
        run: |
          set -x
          echo "Checking if environment variables are loaded..."
          if [ -z "$SUMUP_API_KEY" ]; then
            echo "API key is missing or not set correctly."
            exit 1
          else
            echo "API key is loaded successfully."
            echo "API key length: ${#SUMUP_API_KEY}"
          fi
          
          if [ -z "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
            echo "Google Application Credentials JSON is missing or not set correctly."
            exit 1
          else
            echo "Google Application Credentials JSON is loaded successfully."
            echo "Credentials length: ${#GOOGLE_APPLICATION_CREDENTIALS}"
          fi
        env:
          SUMUP_API_KEY: ${{ secrets.SUMUP_API_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Run the script
        run: |
          set -x
          if [ -f TotalSales2BigQuery.py ]; then
            echo "File TotalSales2BigQuery.py found. Running script."
            python TotalSales2BigQuery.py
          else
            echo "Error: TotalSales2BigQuery.py not found."
            exit 1
          fi
        env:
          SUMUP_API_KEY: ${{ secrets.SUMUP_API_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Print Directory Structure After Script Execution
        run: |
          echo "Current working directory after script execution:"
          pwd
          echo "Directory contents after script execution:"
          ls -la data
        continue-on-error: true  # Continue even if the previous step fails
