name: Run Dummy Data Script

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install google-cloud-bigquery google-cloud-storage google-auth
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          SUMUP_API_KEY: ${{ secrets.SUMUP_API_KEY }}

      - name: Verify Environment Variables
        run: |
          echo "Checking if environment variables are loaded..."
          if [ -z "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
            echo "Google Application Credentials JSON is missing or not set correctly."
            exit 1
          else
            echo "Google Application Credentials JSON is loaded successfully."
            echo "Credentials length: ${#GOOGLE_APPLICATION_CREDENTIALS}"
          fi
          if [ -z "$SUMUP_API_KEY" ]; then
            echo "SumUp API key is missing or not set correctly."
            exit 1
          else
            echo "SumUp API key is loaded successfully."
            echo "API key length: ${#SUMUP_API_KEY}"
          fi

      - name: Print Directory Structure Before Script Execution
        run: |
          echo "Current working directory before script execution:"
          pwd
          echo "Directory contents before script execution:"
          ls -la
          if [ -d "data" ]; then
            echo "Contents of 'data' directory:"
            ls -la data
          else
            echo "'data' directory does not exist."
          fi
        continue-on-error: true

      - name: Run the script
        run: |
          if [ -f "TotalSales2BigQuery.py" ]; then
            echo "File TotalSales2BigQuery.py found. Running script."
            python TotalSales2BigQuery.py
          else
            echo "Error: TotalSales2BigQuery.py not found."
            exit 1
          fi
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          SUMUP_API_KEY: ${{ secrets.SUMUP_API_KEY }}

      - name: Print Directory Structure After Script Execution
        run: |
          echo "Current working directory after script execution:"
          pwd
          echo "Directory contents after script execution:"
          ls -la
          if [ -d "data" ]; then
            echo "Contents of 'data' directory after script execution:"
            ls -la data
          else
            echo "'data' directory does not exist."
          fi
          echo "Checking if CSV file exists at full path:"
          if ls data/TotalSales_*.csv 1> /dev/null 2>&1; then
            echo "CSV file(s) found:"
            ls data/TotalSales_*.csv
          else
            echo "CSV file not found."
          fi
        continue-on-error: true

      - name: Upload CSV file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: csv-file
          path: data/TotalSales_*.csv  # Upload any CSV file generated in the 'data' directory
